# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
