# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160608_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
